# Generated by Django 2.0.2 on 2018-03-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qiita_id',
        ),
    ]
