# Generated by Django 2.0.2 on 2018-03-02 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QiitaEntry',
            fields=[
                ('rendered_body', models.TextField()),
                ('body', models.TextField()),
                ('comments_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('like_count', models.PositiveIntegerField()),
                ('private', models.BooleanField()),
                ('reactions_count', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=128)),
                ('updated_at', models.DateTimeField()),
                ('url', models.URLField()),
                ('page_views_count', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
